# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
    - 2.7

cache: 
    - pip

# Whitelisting
branches:
  only:
    - master


before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
   
   
install: 
    - conda create -q -n python=$TRAVIS_PYTHON_VERSION numpy scipy h5py dateutil matplotlib pandas nose sphinx
    - conda install -c praxes praxes=0.7.1
    - pip install praxes
    #- source activate test_env


# Adopt code from:  https://github.com/rossant/ipycache/blob/master/.travis.yml
script: 
    - "python setup.py install && nosetests test_scan_details.py/"
    - "python setup.py install && nosetests test_summary_plot.py/"